// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AlertController from "./alert_controller"
application.register("alert", AlertController)

import FilePreviewController from "./file_preview_controller"
application.register("file-preview", FilePreviewController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MessageFormController from "./message_form_controller"
application.register("message-form", MessageFormController)

import OnlineIconController from "./online_icon_controller"
application.register("online-icon", OnlineIconController)

import OnlineStatusController from "./online_status_controller"
application.register("online-status", OnlineStatusController)

import SearchController from "./search_controller"
application.register("search", SearchController)
